backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://adolescence.netlify.app"
logo_url: "/images/logo.png"

# Configuração de login manual (sem email)
identity:
  external: false
  registration: false
  manual_login: true  # login direto por usuário e senha

collections:
  - name: "posts"
    label: "Postagens"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Imagem de capa", name: "thumbnail", widget: "image"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Página Inicial"
        name: "home"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
      - file: "sobre.html"
        label: "Sobre"
        name: "about"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
